# This security group defines who/where is allowed to access the Application
# Load Balancer.
# By default, we've opened this up to the public internet (0.0.0.0/0) but can
# you restrict it further if you want.
LoadBalancerSecurityGroup:
  Type: AWS::EC2::SecurityGroup
  Properties:
      VpcId: !Ref VPC
      GroupDescription: Access to the load balancer that sits in front of ECS
      SecurityGroupIngress:
         # Allow access from anywhere to our ECS services
         - CidrIp: 0.0.0.0/0
           IpProtocol: -1
     Tags:
         - Key: Name
           Value: !Sub ${EnvironmentName}-LoadBalancers
