# This security group defines who/where is allowed to access the ECS hosts directly.
# By default we're just allowing access from the load balancer.  If you want to SSH
# into the hosts, or expose non-load balanced services you can open their ports here.
ECSSecurityGroup:
  Type: AWS::EC2::SecurityGroup
  Properties:
      VpcId: !Ref VPC
      GroupDescription: Access to the ECS hosts and the tasks/containers that run on them
      SecurityGroupIngress:
         # Only allow inbound access to ECS from the ELB
         - SourceSecurityGroupId: !Ref LoadBalancerSecurityGroup
           IpProtocol: -1
         - IpProtocol: tcp
           CidrIp: 0.0.0.0/0
           FromPort: '22'
           ToPort: '22'
     Tags:
         - Key: Name
           Value: !Sub ${EnvironmentName}-ECS-Hosts
